# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  motorentaladmin:
    image: motorentaladmin
    build:
      context: .
      dockerfile: src/MotoRental.Admin/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5296:5296
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
