CREATE TABLE motorcycle (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plateNumber varchar NOT NULL,
  year integer NOT NULL,
  model varchar NOT NULL,
  createdAt timestamp NOT NULL DEFAULT (now()),
  updatedAt timestamp
);

CREATE TABLE product (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  createdAt timestamp NOT NULL DEFAULT (now()),
  updatedAt timestamp,
  description varchar,
  numberOfDays integer NOT NULL,
  pricePerDay decimal NOT NULL,
  lateFee decimal,
  isPercent bool
);

CREATE TABLE rental (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  createdAt timestamp NOT NULL DEFAULT (now()),
  startDate timestamp NOT NULL,
  endDate timestamp NOT NULL,
  expectedEndDate timestamp NOT NULL,
  licenseType char(3),
  total decimal,
  productId integer,
  deliveryPersonId integer,
  active bool DEFAULT false
);

CREATE TABLE deliveryPerson (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  userId integer UNIQUE NOT NULL,
  createdAt timestamp NOT NULL DEFAULT (now()),
  updatedAt timestamp,
  name varchar NOT NULL,
  cnpj varchar UNIQUE NOT NULL,
  dateOfBirth timestamp,
  driverLicense varchar UNIQUE NOT NULL,
  licenseType char(3)
);

CREATE TABLE motorcycleRental (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  createdAt timestamp NOT NULL DEFAULT (now()),
  updatedAt timestamp,
  rentalId integer,
  motorcycleId integer,
  active bool DEFAULT true
);

CREATE TABLE users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  createdAt timestamp NOT NULL DEFAULT (now()),
  updatedAt timestamp,
  email varchar UNIQUE NOT NULL,
  password varchar NOT NULL,
  isAdmin bool DEFAULT false
);

CREATE TABLE admins (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  userId integer UNIQUE NOT NULL,
  createdAt timestamp NOT NULL DEFAULT (now()),
  updatedAt timestamp,
  createdByUserId integer NOT NULL,
  name varchar
);

ALTER TABLE rental ADD FOREIGN KEY (productId) REFERENCES product (id);

ALTER TABLE rental ADD FOREIGN KEY (deliveryPersonId) REFERENCES users (id);

ALTER TABLE deliveryPerson ADD FOREIGN KEY (userId) REFERENCES users (id);

ALTER TABLE motorcycleRental ADD FOREIGN KEY (rentalId) REFERENCES rental (id);

ALTER TABLE motorcycleRental ADD FOREIGN KEY (motorcycleId) REFERENCES motorcycle (id);

ALTER TABLE admins ADD FOREIGN KEY (userId) REFERENCES users (id);

ALTER TABLE admins ADD FOREIGN KEY (createdByUserId) REFERENCES users (id);
